-- MySQL Script generated by MySQL Workbench
-- Wed Nov 15 15:15:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BlogDDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BlogDDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BlogDDB` DEFAULT CHARACTER SET utf8 ;
USE `BlogDDB` ;

-- -----------------------------------------------------
-- Table `BlogDDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(255) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusers`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlogDDB`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`categories` (
  `idcategories` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlogDDB`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`articles` (
  `idarticles` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(245) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `published_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `status` INT NOT NULL DEFAULT 0,
  `users_id` INT NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`idarticles`),
  UNIQUE INDEX `title_UNIQUE` (`title` ASC),
  INDEX `fk_articles_users_idx` (`users_id` ASC),
  INDEX `fk_articles_categories1_idx` (`categories_id` ASC),
  CONSTRAINT `fk_articles_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `BlogDDB`.`users` (`idusers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articles_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `BlogDDB`.`categories` (`idcategories`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlogDDB`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`tags` (
  `idtags` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlogDDB`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`comments` (
  `idcomments` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `published_at` DATETIME NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`idcomments`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_comments_articles1_idx` (`articles_id` ASC),
  CONSTRAINT `fk_comments_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `BlogDDB`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BlogDDB`.`articles_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BlogDDB`.`articles_has_tags` (
  `tags_id` INT NOT NULL,
  `articles_id` INT NOT NULL,
  PRIMARY KEY (`tags_id`, `articles_id`),
  INDEX `fk_tags_has_articles_articles1_idx` (`articles_id` ASC),
  INDEX `fk_tags_has_articles_tags1_idx` (`tags_id` ASC),
  CONSTRAINT `fk_tags_has_articles_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `BlogDDB`.`tags` (`idtags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tags_has_articles_articles1`
    FOREIGN KEY (`articles_id`)
    REFERENCES `BlogDDB`.`articles` (`idarticles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
